### ISSUE TITLE
Avatar images shown for trackbacks/pingbacks

### ISSUE THREAD

**Issue by mundschenk-at** [mundschenk-at/avatar-privacy#164]
Trackbacks and pingbacks are technically comments with empty comment author emails. Avatar Privacy should not try to display avatar images for them. 

Reported by @berlindave on the [WP.org support forum](https://wordpress.org/support/topic/avatars-also-showing-up-at-trackbacks/#post-12543550).

**Comment by dshanske** [comment]
Do you use get_avatar_comment_types?

**Comment by dshanske** [comment]
Semantic Linkbacks actually enables avatars on pingbacks where appropriate

**Comment by mundschenk-at** [comment]
I remember the ticket, but no, at the moment I do not use `get_avatar_comment_types()`. Maybe I should. The fix I'm working on does not look at the comment type though, but rather skips avatar lookup if there is no email address (and no user ID) associated with the `WP_Comment`.

**Comment by dshanske** [comment]
That's what I do in the newer code

**Comment by dshanske** [comment]
https://github.com/pfefferle/wordpress-webmention/blob/master/includes/class-webmention-avatar-handler.php

**Comment by mundschenk-at** [comment]
Thanks, I'll look into it. It seems both Webmention and Semantic Linkbacks contain versy similar code regarding avatars. Having a single API function to be used would make things easier (or, I could just duplicate the code again). Semantic Linkbacks needs Webmention, no? So it could just an API in Webmention. Any plans for this?

**Comment by dshanske** [comment]
Semantic Linkbacks is being merged into Webmentions. Slowly. So the code in Semantic Linkbacks is currently disabled if Webmentions is installed

**Comment by mundschenk-at** [comment]
So I'm actually using `get_avatar_comment_types()`, or rather, I use the same code but not the function. However, I was not setting `$args['url'] = false;`. No is there an easy way to generate a `webmention` comment with an avatar on a local installation?

**Comment by dshanske** [comment]
mention yourself? One page to another?

**Comment by mundschenk-at** [comment]
Yes but where does the avatar come from in that case?

**Comment by dshanske** [comment]
It is parsed and the URL stored in the avatar meta key

**Comment by mundschenk-at** [comment]
Yes but where is it taken from? The avatar of the post author?

**Comment by dshanske** [comment]
This is Microformats parsing, so it would look on the page for an author property...so, that would be the avatar of the author.

**Comment by mundschenk-at** [comment]
Thank you.

**Comment by mundschenk-at** [comment]
I've been unable to generate an avatar by using the plugins locally (probably due to the use of `wp_http_validate_url()` which prevents `localhost`-based URLs from working), so I've directly created a comment meta entry in the database. I have what I think will be a sound solution for external image handling in my head, but that will need an additional database table, so it's not for a bugfix release like [2.3.4](https://github.com/mundschenk-at/avatar-privacy/milestone/23).

**Comment by dshanske** [comment]
For now, can you turn control back to WordPress if it isn't a gravatar?

**Comment by mundschenk-at** [comment]
Fixed in #156.
