### ISSUE TITLE
Backfill avatars on old comments

### ISSUE THREAD

**Issue by snarfed** [mundschenk-at/avatar-privacy#269]
Hi! First off, Avatar Privacy is great. Thank you for building and maintaining it!

I'd love for it to backfill avatars on comments that existed before it was initially installed. Is there any way to do that? If not, would you consider it as a feature request? I definitely get that this could be a big project, especially if you tried to do it in the background on the server with eg WP cron, but it might be less work as a WP-CLI command that the user has to run synchronously?

Thanks in advance!

**Comment by mundschenk-at** [comment]
I am assuming you mean Gravatars. Fortunately, the answer is yes: You can enable Gravatars for old comments without explicit consent by enabling `Display Gravatar images by default.` in the settings.

**Comment by snarfed** [comment]
Thanks! I actually wasn't thinking about Gravatar but about remote avatars, ie with remote image URLs, like from the Webmention plugin that @dshanske and @pfefferle maintain. I'd love to fetch and store those avatar images locally, and it sounds like this plugin does that. Ideally, I'd also like to go back through all of the existing comment avatars with remote image URLs on my site, fetch them all, store them, and convert those image URLs to local URLs to the newly stored avatars.

I know that would take extra work in both this plugin and the Webmention plugin, and I don't yet know exactly which work would go where. And I doubt it's a high priority for either you or them, especially since they're currently finishing up a big refactor on their end. Hopefully we can keep this open to track the idea for the future.

**Comment by mundschenk-at** [comment]
Have you tried? If it works at all (which it should, I wrote the remote icon caching code specifically for the Webmentions plugin IIRC), it should work for all past and future remote icons (as there is no consent mechanism involved). The caveat is that I haven't live-tested those things recently.

**Comment by snarfed** [comment]
Hmm, I'm guessing you means it happens on demand, when comments are rendered, not eagerly, right? Or do you really mean that when Avatar Privacy is installed, it immediately iterates through every existing comment stored in the database and fetches and stores its avatar?

**Comment by mundschenk-at** [comment]
It happens on demand, yes. If you wish to prime the image caches, a separate script requesting the avatars would probably be your best solution. 

There are several cache warming plugins in the WP.org repository, those should work too.

**Comment by snarfed** [comment]
Ah, makes sense. Thank you!
