### ISSUE TITLE
Does Not Cache Gravatars received via Webmention 

### ISSUE THREAD

**Issue by dshanske** [mundschenk-at/avatar-privacy#270]
https://github.com/mundschenk-at/avatar-privacy/issues/269

Saw the discussion on this..it works wonderfully for sites that host their own urls... but not of the site with the Webmention happens to use Gravatar, making the URL a Gravatar url.

**Comment by mundschenk-at** [comment]
I'll look into it. Do you have an example case or a way to reproduce on a local installation?

**Comment by mundschenk-at** [comment]
The fix might be as simple as removing the check for `gravatar.com` in https://github.com/mundschenk-at/avatar-privacy/blob/main/includes/avatar-privacy/components/class-avatar-handling.php#L646. I'm not sure there is still a reason for it I think it carried over as stop-gap from before we had proper caching for legacy icon URLs.
