### ISSUE TITLE
Add workaround for broken rest_get_avatar_urls() in REST API

### ISSUE THREAD

**Issue by mundschenk-at** [mundschenk-at/avatar-privacy#39]
The `rest_get_avatar_urls` of the REST API currently only takes an email address instead of a user or comment object, making `get_avatar_url` think its handling an anonymous commenter.

Trac: https://core.trac.wordpress.org/ticket/40030

**Comment by dshanske** [comment]
You too on this problem?

**Comment by mundschenk-at** [comment]
Yeah, I just noticed that `/wp-json/wp/v2/users` was returning (cached) Gravatars on my site when it should have been local avatars. Then I found your trac ticket.
