### ISSUE TITLE
Add shortcode or template function for frontend profile settings

### ISSUE THREAD

**Issue by mundschenk-at** [mundschenk-at/avatar-privacy#69]
Some people like to integrate user profiles and avatar uploads into their frontend. We should provide both a shortcode and an underlying template function (and maybe even a Gutenberg block).

**Comment by florianwalther-private** [comment]
I am also very much for this idea.
Just one suggestion: Please keep the upload functionality simple and decoupled from the media uploader. I've tried lots of other plugins and they always provide an interface that just doesn't look right for a normal user.

**Comment by mundschenk-at** [comment]
Interesting, as I was also considering moving uploads to the Media Library (it has some benefits, such as re-use of existing images and easier switching between them). 

What parts of the UX do you not like specifically, @FlorianWalther?

**Comment by florianwalther-private** [comment]
Maybe I am too inexperienced but when I tried those uploaders from a subscriber role, I had parts in the UI that my normal users shouldn't see. For example fields inserted by other plugins, title + description forms, a dropdown menu for the different months when I (as an admin) added images etc. It's just too much information for a normal image upload functionality and I was worried that another plugin could add some field that would give the users the ability to do harm on my site.
The most popular avatar upload plugin (WP User Avatar) brings its own upload UI with a crop functionality and I like that. However, this plugin doesn't disable Gravatars so I'd rather not use it.
I mean what else is necessary besides "Search on computer" and an upload button?

**Comment by mundschenk-at** [comment]
No, that sounds very reasonable. If there's a way to have "simple" and "advanced" UIs while still integrating with the Media Library.
