### ISSUE TITLE
Compatibility with WP User Manager

### ISSUE THREAD

**Issue by mundschenk-at** [mundschenk-at/avatar-privacy#96]
Disable native profile picture upload and use [WP User Manager's](https://wordpress.org/plugins/wp-user-manager/) if present and activated. Requested by @seanking2919 in the [WordPress.org support forums](https://wordpress.org/support/topic/avatar-privacy-compatibility-with-wp-user-manager/).

**Comment by seanking2919** [comment]
Cool. Thank you for doing this! :D
